## feature process 

In [94]:
import os
import scipy.io as sio
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np

### parameter

In [95]:
PATH_FILE='C:/Users/11488/Desktop/my semg/nina-pro data process/my feature'
NUM_GESTURE=53
DB_FRAMERATE=100
TRIALS=10
NUM_SUBJECT=27
NUM_CHANNEL=10

window_length_ms = 200
window_stride_ms = 10
window = window_length_ms*DB_FRAMERATE/1000
stride = window_stride_ms*DB_FRAMERATE/1000
##see paper Feature reduction and selection for EMG signal classification for more detail
Feature_List=['emg_iemg','emg_mav','emg_mav1','emg_mav2','emg_ssi','emg_var','emg_mavslpphinyomark','emg_mavslp10','emg_mavslpframewise','emg_rms',
              'emg_mavtm3','emg_mavtm4','emg_mavtm5','emg_vorder','emg_log','emg_wl','emg_aac','emg_zc','emg_wl_dasdv','emg_afb9','emg_myop','emg_wamp','emg_hemg15','emg_hemg20',
              'emg_mhw_energy','emg_mtw_energy','emg_arc','emg_cc','emg_mnf_MEDIAN_POWER','emg_mdf_MEDIAN_POWER','emg_pkf','emg_mnp','emg_ttp','emg_smn1','emg_smn2','emg_smn3',
              'emg_fr','emg_psr','emg_vcf'
             ]

In [119]:
len(Feature_List)

39

In [96]:
# my_mat.keys()

### model data and label process

In [121]:
data=np.zeros((14310,39,10,20))
label=[]
for g in range(NUM_GESTURE):
    for s in range(NUM_SUBJECT):
        for t in range(TRIALS):
            mat_path=os.path.join(PATH_FILE,
                                'Subject'+str(s+1),
                                'trial'+str(t),
                                 'Gesture'+str(g)+'.mat'
                                 )
            
            my_mat=sio.loadmat(mat_path)
            for i in range(len(Feature_List)):
                if (i >=6 and i<=8) or (i>=22 and i<=27): #
                    data[g*270+10*s+t,i,:,:]=Mean_reshape(my_mat[Feature_List[i]])
                else:
                    
                    data[g*270+10*s+t,i,:,:]=my_mat[Feature_List[i]]
            label.append(g)
            
            
            
            
            

In [122]:
label=np.array(label)

In [123]:
def Mean_reshape(signal):
    shape=signal.shape
    n=shape[-1]
    res=np.zeros((10,20))
    for i in range(shape[0]):
        for j in range(shape[1]):
            res[i][j]=signal[i][j].sum()/n
    return res

In [127]:
data.shape
label.shape

(14310,)

In [129]:
np.save('C:/Users/11488/Desktop/my semg/nina-pro data process/data.npy', data)

array([3.60988254, 1.72779835, 0.91110267, 1.3017315 , 0.62208357,
       1.49854906, 0.64441922, 1.30177234, 0.73568912, 0.36532069,
       1.99741338, 0.64663808, 0.75970916, 0.51384597, 1.31395222,
       1.37953528, 0.52814168, 2.39722405, 0.53325163, 4.13706092])

In [62]:
data=np.zeros((14310,40,10,20))

(14310, 40, 10, 20)

In [88]:
a=np.zeros((3,4))
a[0,1]=3

In [92]:
a.sum(axis=1)

array([3., 0., 0.])

In [91]:
a

array([[0., 3., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])