## Ninapro-db1 database preprocess

In [2]:
import os
import scipy.io as sio
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from joblib import Parallel, delayed
import emg_features

#### parameter

In [367]:
BASE_PATH='C:/Users/11488/Desktop/my semg/nina-pro data process'
OUT_PATH='C:/Users/11488/Desktop/my semg/nina-pro data process/my dataset'
NUM_GESTURE_G1=12+1
NUM_GESTURE_G2=17+1
NUM_GESTURE_G3=23+1
TOT_NUM_GESTURE=NUM_GESTURE_G1+NUM_GESTURE_G2+NUM_GESTURE_G3-2
SUBJECT=list(range(1,28))

#### init db for each gesture, start with element gesture accessing by key 'gesture'

In [368]:
if os.path.isdir(OUT_PATH) is False:
    os.makedirs(OUT_PATH)
data={}
for g in range(TOT_NUM_GESTURE):
    target_mat=os.path.join(OUT_PATH,
                            'Gesture'+str(g)+'.mat')
    data['gesture']=np.array(g)
    sio.savemat(target_mat, data) 


for db1, there are 3 group of data corresponding to three set of data, each contain 12,17 23 kinds of movements, 0 as the label of rest.

#### process group1 gesture

In [369]:
def Build_Group1_Mat():    
    for s in SUBJECT:
        path_1=os.path.join(BASE_PATH,
                            'raw data',
                            'nina-db1',
                            'group1',
                            'S'+str(s)+'.mat')
        #print(path_1)
        my_mat=sio.loadmat(path_1)
        my_emg=my_mat['emg']
        my_label=np.array([j for [j] in my_mat['restimulus'].astype(np.int32)])
        my_subject=my_mat['subject'].astype(np.int32)[0,0]
        ####
        channel_split=Split_Channel(my_emg) #split signal into channels ,return as a ndarray
        ####
        #Draw_signal(channel_split,s) #draw the raw signal by channel
        ####
        for ch in range(channel_split.shape[0]):
            gesture_split,onset_split=Split_Gesture(channel_split[ch,:],my_label,NUM_GESTURE_G1)
            for ges in range(NUM_GESTURE_G1):
                if ges==0:
                    path_out=os.path.join(OUT_PATH,
                                'Gesture'+str(ges)+'.mat')
                    mat_out=sio.loadmat(path_out)
                    key_ges='gesture_subject'+str(s)+'_channel'+str(ch)
                    mat_out[key_ges]=gesture_split[ges]
                    sio.savemat(path_out, mat_out) 
                else:
                    
                    path_out=os.path.join(OUT_PATH,
                                    'Gesture'+str(ges)+'.mat')
                    mat_out=sio.loadmat(path_out)
                    key_ges='gesture_subject'+str(s)+'_channel'+str(ch)
                    mat_out[key_ges]=gesture_split[ges]
                    key_onset='onset_subject'+str(s)+'_channel'+str(ch)
                    mat_out[key_onset]=onset_split[ges]
                    sio.savemat(path_out, mat_out) 
    return

        

                        

In [370]:
Build_Group1_Mat()

#### process group2 gesture

In [371]:
#group 2 contains 17 gestures plus rest, should change its label to 13-29 in my database
def Build_Group2_Mat():
    for s in SUBJECT:
        path_2=os.path.join(BASE_PATH,
                            'raw data',
                            'nina-db1',
                            'group2',
                            'S'+str(s)+'.mat')
        my_mat=sio.loadmat(path_2)
        my_emg=my_mat['emg']
        my_label=np.array([j for [j] in my_mat['restimulus'].astype(np.int32)])
        my_subject=my_mat['subject'].astype(np.int32)[0,0]
         ####
        channel_split=Split_Channel(my_emg) #split signal into channels ,return as a ndarray
        ####
        #Draw_signal(channel_split,s) #draw the raw signal by channel
        ####
        for ch in range(channel_split.shape[0]):
            gesture_split,onset_split=Split_Gesture(channel_split[ch,:],my_label,NUM_GESTURE_G2)
            for ges in range(NUM_GESTURE_G2):
                if ges==0:
                    path_out=os.path.join(OUT_PATH,
                                    'Gesture'+str(ges)+'.mat')
                    mat_out=sio.loadmat(path_out)
                    key_ges='gesture_subject'+str(s)+'_channel'+str(ch)
                    old_ges=mat_out[key_ges]
                    add_ges=gesture_split[ges]
                    new_ges=Build_Large_list(old_ges,add_ges)
                    mat_out[key_ges]=new_ges
                    sio.savemat(path_out, mat_out)
                else:
                    path_out=os.path.join(OUT_PATH,
                                    'Gesture'+str(ges+12)+'.mat')
                    mat_out=sio.loadmat(path_out)
                    key_ges='gesture_subject'+str(s)+'_channel'+str(ch)
                    mat_out[key_ges]=gesture_split[ges]
                    key_onset='onset_subject'+str(s)+'_channel'+str(ch)
                    mat_out[key_onset]=onset_split[ges]
                    sio.savemat(path_out, mat_out)
    return
            
        
    

In [372]:
Build_Group2_Mat()

#### process group3 gesture

In [373]:
#group 3 contains 23 gestures plus rest, should change its label to 30-52 in my database
def Build_Group3_Mat():
    for s in SUBJECT:
        path_3=os.path.join(BASE_PATH,
                            'raw data',
                            'nina-db1',
                            'group3',
                            'S'+str(s)+'.mat')
        my_mat=sio.loadmat(path_3)
        my_emg=my_mat['emg']
        my_label=np.array([j for [j] in my_mat['restimulus'].astype(np.int32)])
        my_subject=my_mat['subject'].astype(np.int32)[0,0]
         ####
        channel_split=Split_Channel(my_emg) #split signal into channels ,return as a ndarray
        ####
        #Draw_signal(channel_split,s) #draw the raw signal by channel
        ####
        for ch in range(channel_split.shape[0]):
            gesture_split,onset_split=Split_Gesture(channel_split[ch,:],my_label,NUM_GESTURE_G3)
            for ges in range(NUM_GESTURE_G3):
                if ges==0:
                    path_out=os.path.join(OUT_PATH,
                                    'Gesture'+str(ges)+'.mat')
                    mat_out=sio.loadmat(path_out)
                    key_ges='gesture_subject'+str(s)+'_channel'+str(ch)
                    old_ges=mat_out[key_ges]
                    add_ges=gesture_split[ges]
                    new_ges=Build_Large_list(old_ges,add_ges)
                    mat_out[key_ges]=new_ges
                    sio.savemat(path_out, mat_out)
                else:
                    path_out=os.path.join(OUT_PATH,
                                    'Gesture'+str(ges+29)+'.mat')
                    mat_out=sio.loadmat(path_out)
                    key_ges='gesture_subject'+str(s)+'_channel'+str(ch)
                    mat_out[key_ges]=gesture_split[ges]
                    key_onset='onset_subject'+str(s)+'_channel'+str(ch)
                    mat_out[key_onset]=onset_split[ges]
                    sio.savemat(path_out, mat_out)

In [374]:
Build_Group3_Mat()

In [334]:
def Split_Channel(signal):
    channel_set=[]
    for i in range(signal.shape[1]):
        channel_set.append(list(signal[:,i]))
    return np.array(channel_set)

In [335]:
def Draw_signal(signal,s):
    plt.figure(figsize=(40,5))
    for ch in range(signal.shape[0]):
        plt.plot(signal[ch,:],label='channel'+str(ch+1))
    plt.title('signal for subject'+str(s))
    plt.xlabel('n (sample point index)')
    plt.ylabel('Intensity')
    plt.legend(loc="upper right")
    
   
    
    

In [336]:
def Split_Gesture(signal,label,num_gesture):
    if signal.shape!=label.shape:
        print('wrong signal or label shape')
        return 
    else:
        gesture_set=[[] for _ in range(num_gesture)]
        onset_set=[[] for _ in range(num_gesture)]
        count=np.zeros(num_gesture)
        for i in range(signal.shape[0]):
            gesture_set[label[i]].append(signal[i])
            if i >0:
                if (label[i]!=0 and label[i-1]==0) or (label[i]!=0 and label[i-1]!=0):
                    count[label[i]]+=1
                if label[i]==0 and label[i-1]!=0:
                    onset_set[label[i-1]].append(count[label[i-1]])
                    count[label[i-1]]=0
                
                    
                    
#         gesture_set=[np.array(ges,dtype=object) for ges in gesture_set]
#         onset_set=[np.array(ges,dtype=object).astype(np.int32) for ges in onset_set]
        
#     return np.array(gesture_set,dtype=object),np.array(onset_set,dtype=object)
    return gesture_set,onset_set
            
    
    
    

In [360]:
def Build_Large_list(old,add):
    return np.append(old,add)

In [181]:
print(my_mat.keys())

dict_keys(['__header__', '__version__', '__globals__', 'subject', 'exercise', 'stimulus', 'emg', 'glove', 'restimulus', 'repetition', 'rerepetition'])


In [194]:
my_mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Mon Jul 28 14:23:25 2014',
 '__version__': '1.0',
 '__globals__': [],
 'subject': array([[27]], dtype=uint8),
 'exercise': array([[1]], dtype=uint8),
 'stimulus': array([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]], dtype=uint8),
 'emg': array([[0.0024, 0.0049, 0.0049, ..., 0.0024, 0.0024, 0.0708],
        [0.0049, 0.0024, 0.0024, ..., 0.0049, 0.0024, 0.0635],
        [0.0024, 0.0049, 0.0024, ..., 0.0024, 0.0049, 0.0586],
        ...,
        [0.0684, 0.0049, 0.0049, ..., 0.1416, 0.0024, 0.0024],
        [0.0781, 0.0024, 0.0049, ..., 0.1538, 0.0049, 0.0024],
        [0.083 , 0.0024, 0.0024, ..., 0.1611, 0.0049, 0.0049]]),
 'glove': array([[129., 105., 125., ..., 130., 137., 119.],
        [129., 105., 125., ..., 130., 137., 119.],
        [129., 105., 125., ..., 130., 137., 119.],
        ...,
        [138., 103., 120., ..., 177., 139., 113.],
        [138., 103., 120., ..., 177., 

In [77]:
my_mat['emg'][:,0]


array([0.0024, 0.0049, 0.0024, ..., 0.0684, 0.0781, 0.083 ])

In [70]:
my_mat['emg']

array([[0.0024, 0.0049, 0.0049, ..., 0.0024, 0.0024, 0.0708],
       [0.0049, 0.0024, 0.0024, ..., 0.0049, 0.0024, 0.0635],
       [0.0024, 0.0049, 0.0024, ..., 0.0024, 0.0049, 0.0586],
       ...,
       [0.0684, 0.0049, 0.0049, ..., 0.1416, 0.0024, 0.0024],
       [0.0781, 0.0024, 0.0049, ..., 0.1538, 0.0049, 0.0024],
       [0.083 , 0.0024, 0.0024, ..., 0.1611, 0.0049, 0.0049]])

In [284]:
Split_Channel(my_mat['emg'])[0,:]

array([0.0024, 0.0049, 0.0024, ..., 0.0684, 0.0781, 0.083 ])

In [285]:
my_label=[i for [i] in my_mat['restimulus']]
np.array(my_label)

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [286]:
my_mat['subject'].astype(np.int32)[0,0]

27

In [287]:
my_mat['repetition'][1500]

array([2], dtype=uint8)

In [288]:
ges,onset=Split_Gesture(Split_Channel(my_mat['emg'])[0,:],np.array(my_label),NUM_GESTURE_G1)

In [311]:
len(ges[0])

46020

In [298]:
ges[1][-1]

0.1587

In [365]:
onset

[[],
 [498.0, 365.0, 314.0, 273.0, 306.0, 371.0, 333.0, 519.0, 384.0, 311.0],
 [241.0, 367.0, 510.0, 388.0, 296.0, 337.0, 332.0, 598.0, 505.0, 488.0],
 [450.0, 590.0, 505.0, 501.0, 447.0, 590.0, 591.0, 589.0, 347.0, 508.0],
 [271.0, 594.0, 588.0, 589.0, 570.0, 306.0, 239.0, 405.0, 500.0, 398.0],
 [514.0, 274.0, 413.0, 308.0, 279.0, 359.0, 373.0, 263.0, 271.0, 350.0],
 [448.0, 594.0, 555.0, 441.0, 594.0, 426.0, 549.0, 413.0, 424.0, 439.0],
 [296.0, 310.0, 305.0, 331.0, 323.0, 279.0, 428.0, 367.0, 370.0, 188.0],
 [595.0, 586.0, 596.0, 595.0, 488.0, 594.0, 600.0, 595.0, 598.0, 595.0],
 [591.0, 477.0, 591.0, 591.0, 595.0, 591.0, 591.0, 590.0, 329.0, 591.0],
 [588.0, 592.0, 589.0, 585.0, 419.0, 590.0, 535.0, 595.0, 590.0, 596.0],
 [308.0, 376.0, 591.0, 274.0, 547.0, 419.0, 545.0, 592.0, 545.0, 545.0],
 [453.0, 511.0, 394.0, 374.0, 344.0, 439.0, 434.0, 422.0, 530.0, 429.0]]

In [261]:
a=dict()
a['1']=2

In [262]:
a

{'1': 2}