In [112]:
import os
import scipy.io as sio
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from joblib import Parallel, delayed

In [113]:
my_mat=sio.loadmat('C:/Users/11488/Desktop/my semg/nina-pro data process/my dataset/Gesture0')

In [114]:
my_mat

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Fri Jun 11 01:32:03 2021',
 '__version__': '1.0',
 '__globals__': [],
 'gesture': array([[0]]),
 'gesture_subject1_channel0': array([[0.0684, 0.0586, 0.0562, ..., 0.0024, 0.0024, 0.0024]]),
 'gesture_subject1_channel1': array([[0.0024, 0.0024, 0.0024, ..., 0.0024, 0.0024, 0.0024]]),
 'gesture_subject1_channel2': array([[0.0024, 0.0024, 0.0024, ..., 0.0024, 0.0024, 0.0024]]),
 'gesture_subject1_channel3': array([[0.0024, 0.0024, 0.0024, ..., 0.0024, 0.0024, 0.0024]]),
 'gesture_subject1_channel4': array([[0.0024, 0.0024, 0.0024, ..., 0.0024, 0.0024, 0.0024]]),
 'gesture_subject1_channel5': array([[0.0098, 0.0049, 0.0049, ..., 0.0024, 0.0024, 0.0024]]),
 'gesture_subject1_channel6': array([[0.0024, 0.0024, 0.0024, ..., 0.0024, 0.0024, 0.0024]]),
 'gesture_subject1_channel7': array([[0.0488, 0.0415, 0.0391, ..., 0.0513, 0.0488, 0.0439]]),
 'gesture_subject1_channel8': array([[0.0024, 0.0024, 0.0024, ..., 0.127 , 0.1294, 0.1294

In [115]:
my_mat['gesture_subject27_channel0']

array([[0.0024, 0.0049, 0.0024, ..., 0.6079, 0.5908, 0.5444]])

In [72]:
my_mat['gesture_subject27_channel0'].shape

(1, 46020)

In [104]:
my_mat['gesture_subject27_channel0'] ##after change

array([[0.0024, 0.0049, 0.0024, ..., 0.2612, 0.2612, 0.2417]])

In [105]:
my_mat['gesture_subject27_channel0'].shape

(1, 126025)

In [109]:
my_mat['gesture_subject27_channel0'][0][46019]

0.083

In [97]:
my_mat['gesture_subject27_channel0']

array([[0.0024, 0.0049, 0.0024, ..., 0.0684, 0.0781, 0.083 ]])

In [100]:
a=np.append(my_mat['gesture_subject27_channel0'],np.zeros((3)))
a

array([0.0024, 0.0049, 0.0024, ..., 0.    , 0.    , 0.    ])

In [90]:
i=my_mat['gesture_subject27_channel0']

print(i.shape)

(46021,)


[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [110]:

my_mat=sio.loadmat('C:/Users/11488/Desktop/my semg/nina-pro data process/my dataset/Gesture1')

In [111]:
my_mat

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Fri Jun 11 00:46:06 2021',
 '__version__': '1.0',
 '__globals__': [],
 'gesture': array([[1]]),
 'gesture_subject1_channel0': array([[0.0171, 0.0171, 0.0146, ..., 0.0024, 0.0024, 0.0024]]),
 'onset_subject1_channel0': array([[305., 354., 346., 371., 438., 372., 430., 412., 435., 352.]]),
 'gesture_subject1_channel1': array([[0.0073, 0.0244, 0.0269, ..., 0.0024, 0.0024, 0.0024]]),
 'onset_subject1_channel1': array([[305., 354., 346., 371., 438., 372., 430., 412., 435., 352.]]),
 'gesture_subject1_channel2': array([[0.0024, 0.0024, 0.0024, ..., 0.0415, 0.0464, 0.0366]]),
 'onset_subject1_channel2': array([[305., 354., 346., 371., 438., 372., 430., 412., 435., 352.]]),
 'gesture_subject1_channel3': array([[0.0024, 0.0024, 0.0024, ..., 0.0024, 0.0024, 0.0024]]),
 'onset_subject1_channel3': array([[305., 354., 346., 371., 438., 372., 430., 412., 435., 352.]]),
 'gesture_subject1_channel4': array([[0.0024, 0.0024, 0.0024, ..., 0.