In [1]:
import os
import scipy.io as sio
import numpy as np
import matplotlib
import matplotlib.pyplot as plt


In [2]:
BASE_PATH='C:/Users/11488/Desktop/my semg/nina-pro data process'
OUT_PATH='C:/Users/11488/Desktop/my semg/nina-pro data process/my dataset'
NUM_GESTURE_G1=12+1
NUM_GESTURE_G2=17+1
NUM_GESTURE_G3=23+1
TOT_NUM_GESTURE=NUM_GESTURE_G1+NUM_GESTURE_G2+NUM_GESTURE_G3-2
SUBJECT=list(range(1,28))

In [8]:
path_1=os.path.join(BASE_PATH,
                        'raw data',
                        'nina-db1',
                        'group1',
                        'S'+str(1)+'.mat')
    #print(path_1)
my_mat=sio.loadmat(path_1)
my_emg1=my_mat['emg']

In [9]:
path_2=os.path.join(BASE_PATH,
                        'raw data',
                        'nina-db1',
                        'group1',
                        'S'+str(2)+'.mat')
    #print(path_1)
my_mat=sio.loadmat(path_2)
my_emg2=my_mat['emg']

In [24]:
my_emg1[101013]

array([0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0391,
       0.0024, 0.0024])

In [27]:
my_emg2[0]

array([0.0269, 0.1001, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024,
       0.0024, 0.0024])

In [13]:
final=np.vstack((my_emg1,my_emg2))

In [26]:
final[101014]

array([0.0269, 0.1001, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024,
       0.0024, 0.0024])

In [19]:
101014+100686

201700